name: Apply terraform changes to PRODUCTION on GW
on:
  push:
    branches:
      - main
    paths:
      - 'backend/list-s3-items/**'

jobs:
  update-infra-production:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - uses: actions/checkout@v1


      - uses: actions/checkout@v2
      - id: EniltrexAction
        uses: eniltrexAdmin/install-terraform-github-action@v1.0.3
        with:
          version: '1.9.5'
          working-directory: 'install-terraform'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_TERRAFORM_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_TERRAFORM_KEY_SECRET }}
          aws-region: eu-west-3



      - name: Terraform apply
        working-directory: backend/infra/production
        env:
          TF_VAR_bucket_name: ${{ secrets.BUCKET_NAME }}
          TF_VAR_domain_name: ${{ secrets.DOMAIN_NAME }}
        run: |
          terraform init -backend-config="bucket=${{ secrets.TF_STATES_BUCKET }}" \
             -backend-config="key=${{ secrets.BUCKET_NAME}}-s3-browsing/list-lambda/terraform.tfstate" \
             -backend-config="region=eu-west-3"
          terraform plan -out=tfplan -input=false
#          terraform apply  -input=false tfplan